opiproject/godpu

- .golangci.yml
- goopicsi.go
> ci: enhance with .golangci.yml

- .github/workflows/go.yml
> CI: add Codecov

- .github/workflows/go.yml
- README.md
> ci: add coverage badge

- go.sum
- goopicsi.go
- goopicsi_test.go
> Added NullDebugList RPC

- cmd/ipsec/root.go
- cmd/ipsec/test.go
- pkg/ipsec/ipsec.go
Example:
```
docker run --rm -it 88b9bc8c34f6 ipsec test --addr localhost:50151 --pingaddr localhost
```
> move ipsec main from strongswan repo

- .github/workflows/docker-publish.yml
- .github/workflows/linters.yml
- docker-compose.yml
> try Reusing workflows

- .github/workflows/go.yml
> CI: re-use go workflow

- Dockerfile
- cmd/inventory-get.go
- docker-compose.yml
- inventory/inventory.go
> add opi-smbios-server

- storage/backend.go
- storage/frontend.go
- storage/goopicsi.go
- storage/middleend.go
> storage: provide {resource}_id field ion create request

- cmd/evpn-test.go
- network/evpn.go
> evpn: start filling the client

- go.mod
- go.sum
- storage/frontend.go
- storage/goopicsi.go
- storage/goopicsi_test.go
- testing/mock-server/server/server.go
- testing/mock-server/stubs/CreateNVMeSubSystem.json
- testing/mock-server/stubs/CreateNamespace.json
- testing/mock-server/stubs/DeleteNamespace.json
- testing/mock-server/stubs/GetNVMeController.json
- testing/mock-server/stubs/GetNVMeSubSystem.json
> [storage] Rename NVMe -> Nvme

- storage/backend.go
> code duplication

- storage/backend.go
See https://google.aip.dev/122
> [storage] [backend] use full names

- storage/middleend.go
See https://google.aip.dev/122
> [storage] [middleend] use full names

- storage/backend.go
> [backend] testing with and without {resource}_id field

- storage/backend.go
> [backend] parse returned uuid during testing

- storage/middleend.go
> [middleend] testing with and without {resource}_id field

- storage/frontend.go
> [frontend] testing with and without {resource}_id field

- .golangci.yml
- storage/frontend.go
> [nvme] testing with and without {resource}_id field

- storage/backend.go
- storage/frontend.go
- storage/middleend.go
> Update* : send UpdateMask '*' for storage test

- storage/backend.go
- storage/frontend.go
- storage/goopicsi.go
- storage/middleend.go
> TODO: add missing parent field to pass CI

- storage/backend.go
Fixes #203
Had to add sleep to make it work
> [storage] test CreateNVMfRemoteController without {resource}_id

- network/evpn.go
> [evpn] fill get and delete functions

- cmd/evpn-test.go
- network/evpn.go
> [network] add VPC to evpn

- cmd/evpn-test.go
- network/evpn.go
> [evpn] add tunnels/vxlans

- go.mod
- go.sum
- storage/backend.go
- storage/frontend.go
- storage/goopicsi.go
changes to accomodate opi api rpoto changes
@glimchb - pls review
> feat(storage): change id refs to name

- cmd/evpn-test.go
- main.go
- network/evpn.go
Initial implementation of EVPN api's and CLI interface
Changes:
- Added new api's for Logical Bridge, Bridge Port, VRF and SVI
- New CLI interfaces for all the commands
TODO: 
- adding the conf file (usecase: addr field can be place in conf file which is being used in all the commands)  
snap for new cli interface:
> Initial implementation of EVPN api's and CLI interface

- network/evpn.go
on create grpc call, `name` field of the resource itself is ignored
the only legal way to set name is to use `{resource}_id` see https://google.aip.dev/133#user-specified-ids
server will use `{resource}_id` to create `Full Resource Name` see https://google.aip.dev/122#full-resource-names
if `{resource}_id` is not provided, server will generate a random system-generated `{resource}_id` (like uuid, for example) (edited) 
> fix(evpn): must use {resource}_id on create

- docker-compose.yml
> ci: fail opi-test if any specific tests fail

- network/utils.go
> refactor(evpn): use ParseCIDR to reduce code

- go.mod
- go.sum
- storage/middleend.go
see https://github.com/opiproject/opi-api/pull/344
> Feat middleend annotations

- go.mod
- go.sum
- storage/frontend.go
see https://github.com/opiproject/opi-api/pull/375
> feat(storage/frontend) target api support

- storage/backend.go
failed due to https://github.com/spdk/spdk/issues/3077
> [storage] enable TLS backend tests

- docker-compose.yml
fixes https://github.com/opiproject/godpu/issues/353
> fix(evpn): use frr_addr to reach frr container

- cmd/storage-test.go
- storage/frontend.go
Continuation of https://github.com/opiproject/godpu/pull/364
> feat(storage): run tests for a part of frontend partition

- storage/test/resource.go
Need opi-spdk-bridge patch to pass ci https://github.com/opiproject/opi-spdk-bridge/pull/879
> fix: full resource names to resource names in names

- Makefile
- cmd/network/evpn-bridge-port.go
- cmd/network/evpn-logical-brige.go
- cmd/network/evpn-svi.go
- cmd/network/evpn-utils.go
- cmd/network/evpn-vrf.go
- go.mod
- go.sum
this PR includes fixes and additions for evpn.
1. build support for arm
2. added component and gwip prefixes printing in human readable format.
3. miner correction in logs after testing
> Build support for arm and use latest evpn opi-api
