opiproject/godpu

go.sum
goopicsi.go

add ConnectToRemoteAndExpose function

---

.github/dependabot.yml
go.mod

[Update go version to 1.19 in go.mod](https://github.com/opiproject/goopicsi/commit/fee7cc068c228a4bc04709e32971674f98e6a74d)

Update go version to 1.19 in go.mod

---

go.sum
goopicsi.go
goopicsi_test.go

Added the below RPCs:
NVMfRemoteControllerGet
NVMfRemoteControllerList

Added Get and List RPC

---

goopicsi.go
goopicsi_test.go

Added DeleteNamespace RPC
Signed-off-by: Harish P <harish_p4@dell.com>

Added DeleteNamespace RPC

---

go.sum
goopicsi.go
goopicsi_test.go

Added CreateNVMeSubsystem RPC
Added CreateNVMeController RPC

CreateNVMeSubsystem RPC

---

go.mod
go.sum
goopicsi.go
goopicsi_test.go

Generate HostNQN

---

go.sum
goopicsi.go
goopicsi_test.go

Change Id type to String

---

goopicsi.go

Comment for NVMeSubsystem

---

Dockerfile
pkg/csi/goopicsi.go
pkg/csi/goopicsi_test.go
pkg/inventory/inventory.go
pkg/inventory/inventory_test.go

add inventory package

---

Dockerfile
cmd/inventory/get.go
cmd/inventory/root.go
cmd/ipsec/root.go
cmd/ipsec/stats.go
cmd/root.go
main.go

```$ docker run fc9e0e4dcd2b --help
godpu - DPUs and IPUs cli commands
Usage:
godpu [flags]
godpu [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
inventory   DPUs and IPUs inventory commands
ipsec       DPUs and IPUs ipsec commands
Flags:
-h, --help   help for godpu
Use "godpu [command] --help" for more information about a command.
```

fixing cobra cli

---

storage/frontend.go

Use URI for volumes for frontend devices as temporary solution since they are used in OPI API [NVMe](https://github.com/opiproject/opi-api/blob/432a550f4f6c6577a133d03f00f1373764994fd5/storage/v1alpha1/frontend_nvme_pcie.proto#L29), [virtio-blk](https://github.com/opiproject/opi-api/blob/432a550f4f6c6577a133d03f00f1373764994fd5/storage/v1alpha1/frontend_virtio_blk.proto#L27) and [scsi ](https://github.com/opiproject/opi-api/blob/432a550f4f6c6577a133d03f00f1373764994fd5/storage/v1alpha1/frontend_virtio_scsi.proto#L61) devices. Will be changed after a URI path discussion in OPI API.
CI should path with https://github.com/opiproject/opi-spdk-bridge/pull/432.

Use fullnames in frontend

---

cmd/inventory-get.go
cmd/ipsec-stats.go
cmd/storage-test.go
docker-compose.yml
main.go

Current                           NOW(with HIERARCHY)
godpu get                  --->   godpu inventory get
godpu stats                --->   godpu ipsec stats
godpu test                  --->   godpu ipsec test
godpu storage-test    --->   godpu storage test

fix(issue160): hierarchical command structure

---

docker-compose.yml
go.mod
go.sum
storage/backend.go
storage/goopicsi.go

https://github.com/opiproject/opi-api/pull/343

feat(storage/backend): opi-api added TcpController and FabricsPath

---

storage/frontend.go

An error will be sent to non-zero port/vf values for vhosr-user-blk transport in opi-spdk-bridge

fix(frontned): use zero port/vf for virtio-blk

---

docker-compose.yml

Reverts opiproject/godpu#349 since it was not ready

Revert "fix: opi-test is started only when all dependent services completed"

---

cmd/storage-test.go

Division on sub-partitions will be provided in follow-up patches

feat(storage): run tests for specific API partition

---

cmd/storage-nvme-controller.go
cmd/storage.go
storage/nvme_controller.go
storage/nvme_controller_test.go

```bash
ss0=$(/dpu storage create nvme subsystem --nqn nqn.2019-06.io.spdk:opicli0 --hostnqn nqn.2019-06.io.spdk:opi-host0 --id subsys0)
ss1=$(/dpu storage create nvme subsystem --nqn nqn.2019-06.io.spdk:opicli1 --id subsys1)
tcp0=$(/dpu storage create nvme controller tcp --subsystem "$ss0" --ip "127.0.0.1" --port 4420 --id nvmetcp0)
pcie0=$(/dpu storage create nvme controller pcie --subsystem "$ss1" --port 0 --pf 0 --vf 1 --id pcie0)
/dpu storage delete nvme controller --name "$pcie0"
/dpu storage delete nvme controller --name "$tcp0"
/dpu storage delete nvme subsystem --name "$ss1"
/dpu storage delete nvme subsystem --name "$ss0"
```

feat(storage): add create/delete cli calls for nvme tcp/pcie controllers

---

cmd/storage-virtio-blk.go
cmd/storage.go
storage/client.go
storage/nvme_controller.go
storage/nvme_controller_test.go
storage/nvme_namespace.go
storage/nvme_namespace_test.go
storage/nvme_subsystem.go
storage/nvme_subsystem_test.go
storage/virtio_blk.go
storage/virtio_blk_test.go

```bash
blk0=$(/dpu storage create virtio blk --id virtioblk0 --pf 0 --vf 0 --volume "$vol0")
/dpu storage delete virtio blk --name "$blk0"
```

feat(storage): add create/delete cli calls for virtio-blk controllers 

---

storage/client.go

Context is used to set timeout

refactor(storage): remove unused timout from client

---

go.mod
go.sum
storage/backend.go
storage/goopicsi.go
storage/resource.go

Continuation of https://github.com/opiproject/opi-api/pull/412
CI test [fails](https://github.com/opiproject/godpu/actions/runs/7181167771/job/19555010129?pr=410#step:9:464) since we use opi-spdk-bridge from the main branch, which does not contain api update yet

fix(storage/backend): adjust nvme to parent member.

---

cmd/storage/backend/backend.go
cmd/storage/backend/nvme_controller.go
cmd/storage/storage.go
storage/backend/client.go
storage/backend/client_test.go
storage/backend/nvme_controller.go
storage/backend/nvme_controller_test.go

Exemplary cmd:
```bash
nvmf0=$(/dpu storage create backend nvme controller --id nvmf0 --multipath failover)
/dpu storage delete backend nvme controller --name "$nvmf0"
```

feat(storage/nvme): add cli for nvme controller

---

cmd/storage/backend/backend.go
cmd/storage/backend/nvme_path.go
storage/backend/nvme_path.go
storage/backend/nvme_path_test.go

Exemplary cmds to connect to a remote NVMe/TCP controller:
```bash
nvmf0=$(go run . storage create backend nvme controller --id nvmef0 --multipath failover)
path0=$(go run . storage create backend nvme path tcp --controller "$nvmf0" --id path0 --ip 127.0.0.1 --port 4420 --nqn nqn.2019-06.io.spdk:0)
go run . storage delete backend nvme path --name $path0
go run . storage delete backend nvme controller --name $nvmf0
nvme0=$(go run . storage create backend nvme controller --id nvmee0 --multipath disable)
path0=$(go run . storage create backend nvme path pcie --controller "$nvme0" --id path0 --bdf "0000:65:00.0")
go run . storage delete backend nvme path --name $path0
go run . storage delete backend nvme controller --name $nvme0
```

 feat(storage/nvme): add cli for backend nvme path

---

cmd/inventory/inventory-get.go
cmd/ipsec/ipsec-stats.go
cmd/ipsec/ipsec-test.go
cmd/network/evpn-bridge-port.go
cmd/network/evpn-logical-brige.go
cmd/network/evpn-svi.go
cmd/network/evpn-test.go
cmd/network/evpn-vrf.go
main.go

continuation of https://github.com/opiproject/godpu/pull/430

refactor: move cmd files in dedicated dirs

---

storage/test/resource.go

the used parent collection names are not consistent with ones described in [API](https://github.com/opiproject/opi-api/blob/main/storage/frontend_nvme.proto)
CI requires https://github.com/opiproject/opi-spdk-bridge/pull/880 to pass

fix(storage/frontend): precede nvme parent collections with nvme

---

cmd/inventory/inventory-get.go
cmd/ipsec/ipsec-stats.go
cmd/ipsec/ipsec-test.go
cmd/network/evpn-bridge-port.go
cmd/network/evpn-logical-brige.go
cmd/network/evpn-svi.go
cmd/network/evpn-test.go
cmd/network/evpn-vrf.go
cmd/storage/backend/backend.go
cmd/storage/backend/nvme_controller.go
cmd/storage/backend/nvme_path.go
cmd/storage/frontend/frontend.go
cmd/storage/frontend/nvme_controller.go
cmd/storage/frontend/nvme_namespace.go
cmd/storage/frontend/nvme_subsystem.go
cmd/storage/frontend/virtio_blk.go
cmd/storage/storage.go
cmd/storage/test.go
inventory/client_test.go
main.go

fixing a new golangci-lint check
unblocks https://github.com/opiproject/godpu/pull/440

refactor: rename unused vars to underscores
